[workspace]
dependencies_update = true 
pr_branch_prefix = "release-" 
pr_labels = ["release"] # add the `release` label to the release Pull Request
publish_timeout = "10m" # set a timeout for `cargo publish`

[[cli]]
name = "cabin-cli"
semver_check = true
changelog_path = "docs/CHANGELOG.md" 

[[db]]
name = "cabin-db"
semver_check = true
changelog_path = "docs/CHANGELOG.md" 

[[storage]]
name = "cabin-storage"
semver_check = true
changelog_path = "docs/CHANGELOG.md" 

[[vdbe]]
name = "cabin-vdbe"
semver_check = true
changelog_path = "docs/CHANGELOG.md"


[changelog]
protect_breaking_commits = true # always include commits with breaking changes in the changelog
