[workspace]
dependencies_update = true
pr_branch_prefix = "release-"
pr_labels = ["release"] # add the `release` label to the release Pull Request
publish_timeout = "10m" # set a timeout for `cargo publish`
git_release_enable = false
publish_allow_dirty = false
git_tag_enable = true

[[package]]
name = "cabin-cli"
changelog_path = "cli/docs/CHANGELOG.md"
publish=true

[[package]]
name = "cabin-db"
changelog_path = "db/docs/CHANGELOG.md"
publish=true

[[package]]
name = "cabin-storage"
changelog_path = "storage/docs/CHANGELOG.md"
publish=true

[[package]]
name = "cabin-vdbe"
changelog_path = "vdbe/docs/CHANGELOG.md"
publish=true


[changelog]
protect_breaking_commits = true # always include commits with breaking changes in the changelog
