[workspace]
dependencies_update = true
pr_branch_prefix = "release-"
pr_labels = ["release"] # add the `release` label to the release Pull Request
publish_timeout = "10m" # set a timeout for `cargo publish`

[[package]]
name = "cabin-cli"
semver_check = true
changelog_path = "cli/docs/CHANGELOG.md"
publish=true

[[package]]
name = "cabin-db"
semver_check = true
changelog_path = "db/docs/CHANGELOG.md"
publish=true

[[package]]
name = "cabin-storage"
semver_check = true
changelog_path = "storage/docs/CHANGELOG.md"
publish=true

[[package]]
name = "cabin-vdbe"
semver_check = true
changelog_path = "vdbe/docs/CHANGELOG.md"
publish=true


[changelog]
protect_breaking_commits = true # always include commits with breaking changes in the changelog
