[package]
name = "cabin-storage"
version = "0.1.2"
edition = "2024"
license = "AGPL-3.0"
description = "LSMTree based storage engine"

[dependencies]
anyhow = "1.0.99"
bytes = "1.10.1"
crossbeam-skiplist = "0.1.3"
ouroboros = "0.18.5"
