name: release.yml
on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: intall rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: install cargo-nextest
        uses: taiki-e/install-action@cargo-nextest

      - name: run clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: check formatting
        run: cargo fmt --all --check

      - name: run tests
        run: cargo nextest run

  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: "${{ secrets.RELEASE_PLEASE }}"
          release-type: rust
